// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import GameController from "./game_controller"
application.register("game", GameController)

import SetColorSchemeController from "./set_color_scheme_controller"
application.register("set-color-scheme", SetColorSchemeController)